# Generated by Django 5.2.1 on 2025-11-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("KITCHEN_STAFF", "Kitchen Staff"), ("COURIER", "Courier")],
                max_length=20,
            ),
        ),
    ]
