# Generated by Django 5.2.1 on 2025-11-05 08:15

from django.db import migrations


def populate_first_names_from_email(apps, schema_editor):
    """
    Finds users with empty first/ names and populates them
    by splitting their email.

    e.g., 'john.doe@example.com' -> "John", "Doe"
    e.g., 'admin@example.com' -> "Admin", "User"
    """
    user_model = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias

    users_to_update = user_model.objects.using(db_alias).filter(first_name="")

    for user in users_to_update:
        email = user.email
        if not email:
            # Can't do anything, just give them a placeholder
            user.first_name = "Unnamed"
        else:
            local_part = email.split("@")[0]
            # Clean up common separators like '.' or '_'
            name_parts = local_part.replace(".", " ").replace("_", " ").title().split()

            if len(name_parts) >= 2:
                user.first_name = (name_parts[0])[:50]  # Limit first name length
            else:
                # Fallback for emails like 'admin'
                user.first_name = (local_part)[:50]

        user.save(using=db_alias, update_fields=["first_name"])


def populate_last_names_from_email(apps, schema_editor):
    """
    Finds users with empty last names and populates them
    by splitting their email.

    e.g., 'john.doe@example.com' -> "John", "Doe"
    e.g., 'admin@example.com' -> "Admin", "User"
    """
    user_model = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias

    users_to_update = user_model.objects.using(db_alias).filter(last_name="")

    for user in users_to_update:
        email = user.email
        if not email:
            # Can't do anything, just give them a placeholder
            user.last_name = "User"
        else:
            local_part = email.split("@")[0]
            # Clean up common separators like '.' or '_'
            name_parts = local_part.replace(".", " ").replace("_", " ").title().split()

            if len(name_parts) >= 2:
                user.last_name = (" ".join(name_parts[1:]))[:50]  # Limit last name length
            else:
                # Fallback for emails like 'admin'
                user.last_name = "User"  # A sensible default

        # We must save each user
        user.save(using=db_alias, update_fields=["last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(populate_first_names_from_email, migrations.RunPython.noop),
        migrations.RunPython(populate_last_names_from_email, migrations.RunPython.noop),
    ]
