# Generated by Django 5.2.1 on 2025-12-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_username_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager"),
                    ("KITCHEN_STAFF", "Kitchen Staff"),
                    ("COURIER", "Courier"),
                    ("CASHIER", "Cashier"),
                ],
                max_length=20,
            ),
        ),
    ]
