repos:
  # 1. Black (Форматування коду)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12

  # 2. isort (Сортування імпортів)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        # isort автоматично знайде конфігурацію у pyproject.toml

  # 3. Flake8 (Лінтинг коду)
#  - repo: https://github.com/pycqa/flake8
#    rev: 7.3.0
#    hooks:
#      - id: flake8
        # Додаємо розширення: bugbear, bandit та mccabe
#        additional_dependencies:
#          - flake8-bugbear==24.4.26
#          - flake8-bandit==4.1.1
#          - mccabe==0.7.0
#        # Flake8 автоматично знайде конфігурацію у pyproject.toml
#  - repo: local
#    hooks:
#      - id: generate-static-analysis-report
#        name: Generate static-analysis.md Report
#        entry: scripts/generate_report.sh
#        language: system
#        files: \.(py)$
#        always_run: true
#        pass_filenames: false 