# Generated by Django 5.2.1 on 2025-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly назва категорії (автоматично генерується).",
                max_length=100,
                unique=True,
            ),
        ),
    ]
