# Generated by Django 5.2.1 on 2025-11-02 13:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from="name", unique=True),
        ),
    ]
