# Generated by Django 5.2.1 on 2025-12-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_order_courier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.DeleteModel(
            name="DishIngredient",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
