# Generated by Django 5.2.1 on 2025-12-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_remove_dish_ingredients_delete_dishingredient_and_more"),
    ]

    # delivery_address about to become non-nullable, insert empty strings
    operations = [
        migrations.RunSQL(
            """
            UPDATE restaurant_order
            SET delivery_address = ''
            WHERE self_pickup = TRUE AND (delivery_address IS NULL OR delivery_address = '');
            """,
            reverse_sql="""
            UPDATE restaurant_order
            SET delivery_address = NULL
            WHERE self_pickup = TRUE AND delivery_address = '';
            """,
        ),
    ]
