# Generated by Django 5.2.1 on 2025-12-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_empty_str_address_for_self_pickup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True, default="", verbose_name="Delivery address"),
            preserve_default=False,
        ),
    ]
