# Generated by Django 5.2.1 on 2025-12-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_order_delivery_type_kitchen_status"),
        ("restaurant", "0009_alter_order_delivery_address"),
    ]

    operations = []
