# Generated by Django 5.2.1 on 2025-12-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_merge_20251208_2258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In progress"),
                    ("waiting_for_courier", "Waiting for courier"),
                    ("delivering", "Delivering"),
                    ("paid_credit", "Paid (credit)"),
                    ("awaiting_cash", "Awaiting cash payment"),
                    ("paid_cash", "Paid (cash)"),
                    ("picked_up", "Picked up"),
                ],
                default="new",
                max_length=32,
            ),
        ),
    ]
