services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./startup.sh
    volumes:
      - ./delivery-service:/app
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PASSWORD}@db:${PG_PORT}/${PG_DATABASE}
      - PYTHONUNBUFFERED=1
      - DJANGO_LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
